### ISSUE TITLE
Color on Linux vs Mac

### ISSUE THREAD

**Issue by hahuang65** [nvim-neotest/neotest#43] opened 2022-06-27 20:28 UTC
Using the exact same `init.lua` on macOS and Arch Linux, I have different symbols colors.

On macOS, they're colored (green check mark, yellow running, red failed).
On Arch, it's just all white/light grey... 

How can I get them to have the same behavior?

**Comment by rcarriga** [comment] 2022-06-28 07:08
I'm going to need a more info to debug properly. First check that `:echo termguicolors` prints 1, if not then I'm guessing the mac install has a runtime file that enables it where the linux one does not. If they're both 1 then please test with the following init.lua

```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))
vim.opt.termguicolors = true

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
  vim.cmd("packadd packer.nvim")
  install_plugins = true
end

local packer = require("packer")

packer.init({
  package_root = test_dir .. "/pack",
  compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
  -- Packer can manage itself
  use("wbthomason/packer.nvim")

  use("vim-test/vim-test")
  use({
    "nvim-neotest/neotest",
    requires = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "antoinemadec/FixCursorHold.nvim",
      "nvim-neotest/neotest-python",
    },
    config = function()
      require("neotest").setup({
        adapters = { require("neotest-python") },
      })
    end,
  })

  if install_plugins then
    packer.sync()
  end
end)

vim.cmd[[
command! NeotestSummary lua require("neotest").summary.toggle()
command! NeotestFile lua require("neotest").run.run(vim.fn.expand("%"))
command! Neotest lua require("neotest").run.run(vim.fn.getcwd())
command! NeotestNearest lua require("neotest").run.run()
command! NeotestDebug lua require("neotest").run.run({ strategy = "dap" })
command! NeotestAttach lua require("neotest").run.attach()
]]
```

**Comment by hahuang65** [comment] 2022-06-30 17:57
Weirdly... `:echo termguicolors` gives me a `E121: Undefined variable: termguicolors`...

I do have
```
opt.termguicolors = true   -- Enables 24-bit colors in the TUI. Uses `gui` highlights instead of `cterm`
```

in my `init.lua` though...

**Comment by rcarriga** [comment] 2022-07-02 07:35
Ah sorry yep was supposed to be `echo &termguicolors`. Can you try with the init.lua above and see if you see the same?

**Comment by hahuang65** [comment] 2022-07-02 15:01
This is weird... Now it's flipped for me. Arch Linux has color, Mac doesn't. I wonder if it has to do with nvim version...

This is with your config above on both machines.

**Comment by rcarriga** [comment] 2022-07-02 16:05
What versions are you using? You could try with the app image from the GitHub releases https://github.com/neovim/neovim/releases on both

**Comment by hahuang65** [comment] 2022-07-02 16:35
I'm building nightlies... So the versions will vary day by day.

Feel free to close this bug if you want, as it's not a deal breaking bug.

But if you keep it open, I'm happy to keep poking at it to see what's causing it. 

I'll post here with any findings. I don't want to burden you any more with this issue.

**Comment by rcarriga** [comment] 2022-07-02 18:36
I'll keep it open for now :+1: Please do update if you find the cause!

**Comment by hahuang65** [comment] 2022-07-05 19:10
Weird... it seems random when I open nvim. Sometimes it gets color, other times it doesn't.

**Comment by rcarriga** [comment] 2022-08-03 08:43
Going to close this as I haven't seen anyone else experience this issue so it's likely config related

**Closed by rcarriga** 2022-08-03 08:43 UTC
